### ISSUE TITLE
build on openbsd 5.9

### ISSUE THREAD

**Issue by edgarpettijohn** [shevek/libspf2#16]
gcc -DHAVE_CONFIG_H -I. -I../..  -I../../src/include -I../../src   -g -O2 -Wall -MT spfquery.o -MD -MP -MF .deps/spfquery.Tpo -c -o spfquery.o spfquery.c
mv -f .deps/spfquery.Tpo .deps/spfquery.Po
/bin/sh ../../libtool  --tag=CC   --mode=link gcc  -g -O2 -Wall   -o spfquery spfquery.o ../../src/libspf2/libspf2.la -lpthread 
libtool: link: gcc -g -O2 -Wall -o .libs/spfquery spfquery.o  -L../../src/libspf2/.libs -lspf2 -lpthread -Wl,-rpath,/usr/local/lib
../../src/libspf2/.libs/libspf2.so.3.0: warning: warning: strcpy() is almost always misused, please use strlcpy()
spfquery.o: In function `main':
/home/libspf2/src/spfquery/spfquery.c:635: warning: warning: strcat() is almost always misused, please use strlcat()
../../src/libspf2/.libs/libspf2.so.3.0: warning: warning: sprintf() is often misused, please use snprintf()
../../src/libspf2/.libs/libspf2.so.3.0: undefined reference to `res_close'
collect2: ld returned 1 exit status
Makefile:439: recipe for target 'spfquery' failed
gmake[4]: *** [spfquery] Error 1
gmake[4]: Leaving directory '/home/libspf2/src/spfquery'
Makefile:488: recipe for target 'all-recursive' failed
gmake[3]: *** [all-recursive] Error 1
gmake[3]: Leaving directory '/home/libspf2/src/spfquery'
Makefile:353: recipe for target 'all-recursive' failed
gmake[2]: *** [all-recursive] Error 1
gmake[2]: Leaving directory '/home/libspf2/src'
Makefile:408: recipe for target 'all-recursive' failed
gmake[1]: *** [all-recursive] Error 1
gmake[1]: Leaving directory '/home/libspf2'
Makefile:338: recipe for target 'all' failed
gmake: *** [all] Error 2

steps to reproduce:

# AUTOMAKE_VERSION=1.15 AUTOCONF_VERSION=2.69 ./bootstrap
# ./configure
# AUTOMAKE_VERSION=1.15 AUTOCONF_VERSION=2.69 gmake

**Comment by bdijkstra82** [comment]
It builds if you add 
`shlib_dirs=/usr/local/lib/libbind`
to /etc/rc.conf.local and then reboot or run ldconfig(8).

**Comment by schmonz** [comment]
This can be fixed by merging #28.
