### ISSUE TITLE
Can't build on OSX 10.9

### ISSUE THREAD

**Issue by eaigner** [shevek/libspf2#4]
Running

```
./configure
make
```

produces

```
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../.. -I../../src/include -I../../src -g -O2 -Wall -MT spf_compile.lo -MD -MP -MF .deps/spf_compile.Tpo -c spf_compile.c  -fno-common -DPIC -o .libs/spf_compile.o
spf_compile.c:580:5: error: expected expression
                                SPF_debugf("Adding literal %%");
                                ^
../../src/include/spf_log.h:66:86: note: expanded from macro 'SPF_debugf'
#define SPF_debugf(format, ... ) SPF_debugx( __FILE__, __LINE__, format, __VA_ARGS__ )
                                                                                     ^
spf_compile.c:589:5: error: expected expression
                                SPF_debugf("Adding literal space");
                                ^
../../src/include/spf_log.h:66:86: note: expanded from macro 'SPF_debugf'
#define SPF_debugf(format, ... ) SPF_debugx( __FILE__, __LINE__, format, __VA_ARGS__ )
                                                                                     ^
spf_compile.c:598:5: error: expected expression
                                SPF_debugf("Adding escaped space");
                                ^
../../src/include/spf_log.h:66:86: note: expanded from macro 'SPF_debugf'
#define SPF_debugf(format, ... ) SPF_debugx( __FILE__, __LINE__, format, __VA_ARGS__ )
                                                                                     ^
spf_compile.c:608:15: warning: format specifies type 'int' but the argument has type 'size_t' (aka 'unsigned long') [-Wformat]
                                src[idx], idx);
                                          ^~~
../../src/include/spf_log.h:66:74: note: expanded from macro 'SPF_debugf'
#define SPF_debugf(format, ... ) SPF_debugx( __FILE__, __LINE__, format, __VA_ARGS__ )
                                                                         ^
1 warning and 3 errors generated.
make[4]: *** [spf_compile.lo] Error 1
make[3]: *** [all-recursive] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```
